
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container-nginx
    image: 10.99.87.210:5000/nginx:latest
  imagePullSecrets:
  - name: regcred

